CREATE TABLE IF NOT EXISTS STOCK (
   ID INT NOT NULL,
   NAME varchar(250) NOT NULL,
   DESCRIPTION varchar(250) NOT NULL,
   CURRENT_PRICE NUMERIC(10,2),
   LAST_UPDATE timestamp NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS STOCK_EXCHANGE (
    ID BIGINT NOT NULL,
    NAME varchar(250) NOT NULL,
    DESCRIPTION varchar(250) NOT NULL,
    LIVE_IN_MARKET Boolean,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS STOCK_EXCHANGE_STOCK (
    STOCK_EXCHANGE_ID BIGINT NOT NULL,
    STOCK_ID BIGINT NOT NULL,
    PRIMARY KEY (STOCK_EXCHANGE_ID, STOCK_ID),
    CONSTRAINT FK_STOCK_EXCHANGE_ID FOREIGN KEY (STOCK_EXCHANGE_ID) REFERENCES STOCK_EXCHANGE(ID),
    CONSTRAINT FK_STOCK_ID FOREIGN KEY (STOCK_ID) REFERENCES STOCK(ID)
);